version: '3'

tasks:
  default:
    cmds:
      - task: prepare
      - task: test
      - task: govulncheck
      # - task: nancy

  test:
    desc: Test and lint.
    cmds:
      - go mod verify
      - go test -shuffle on ./...
      - golangci-lint-v2 run --enable gosec --timeout 3m0s ./...
    sources:
      - ./go.mod
      - '**/*.go'

  govulncheck:
    desc: Check reachable vulnerabilities with latest govulncheck.
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...
    sources:
      - ./go.mod
      - '**/*.go'

  nancy:
    desc: Check vulnerability of external packages with Nancy.
    cmds:
      - depm list -j | nancy sleuth -n
    sources:
      - ./go.mod
      - '**/*.go'

  prepare:
    cmds:
      - go mod tidy -v -go=1.25.10

  clean:
    desc: Initialize module and build cache, and remake go.sum file.
    cmds:
      - rm -f ./go.sum
      - go clean -cache
      - go clean -modcache
